export const SIGNUP_STARTED = "SIGNUP_STARTED";
export const SIGNUP_SUCCEEDED = "SIGNUP_SUCCEEDED";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const SIGNIN_STARTED = "SIGNUP_STARTED";
export const SIGNIN_SUCCEEDED = "SIGNUP_SUCCEEDED";
export const SIGNIN_FAILED = "SIGNUP_FAILED";

